### ISSUE TITLE
Which version of VS did you use for FAP?

### ISSUE THREAD

**Issue by wanglin95** [N00byEdge/FAP#2]
Which version of VS did you use for FAP?I compiled  it with VS2013 and a lot of weird problems appeared.

**Comment by N00byEdge** [comment]
FAP is made for VS2017 with C++17 features, just like the latest version of BWAPI. If you want to look at existing usage, take a look at the Tests directory: https://github.com/N00byEdge/FAP/blob/master/Tests/DataLoad.cpp
If you need any help, feel free to reach out to me here or on Discord: N00byEdge#5555 or through the BWAPI discord

**Comment by wanglin95** [comment]
OK, thank you very much!

**Comment by wanglin95** [comment]
In the NoLockup.cpp of the Tests project:   #include "gtest/gtest.h", 
the source file could not be opened, I can't find this file either.

**Comment by N00byEdge** [comment]
The gtest test adapter for VS needs to be installed to compile the tests for FAP.

**Comment by wanglin95** [comment]
I don't quite understand the meaning of Dataload.cpp. Now I want to simulate a battle, specify the army of both sides, and then get the winning rate. Is the simulation done by editing and modifying the Tests project?

**Comment by N00byEdge** [comment]
@wanglin95 The Tests project is purely for testing FAP functionality when adding or changing code while developing FAP. Only the FAP project should be used by bots or other things which need combat simulation.

**Comment by wanglin95** [comment]
@N00byEdge So, how to simulate combat with FAP? How to specify the two combat units? I still don't understand how to use it.

**Comment by N00byEdge** [comment]
As you see in the tests, you create a simulation with

`FAP::FastAPproximation<> fap;`

then add units to it

```
  fap.addUnitPlayer1(
    FAP::makeUnit()
      .setUnitType(BWAPI::UnitTypes::Terran_Marine)
      .setPosition({0, 0})
      .setHealth(BWAPI::UnitTypes::Terran_Marine.maxHitPoints())
      .setShields(BWAPI::UnitTypes::Terran_Marine.maxShields())
      .setFlying(false)
      .setElevation(-1)
      .setAttackerCount(0)
      .setArmorUpgrades(0)
      .setAttackUpgrades(0)
      .setShieldUpgrades(0)
      .setSpeedUpgrade(false)
      .setAttackSpeedUpgrade(false)
      .setAttackCooldownRemaining(0)
      .setStimmed(false)
      .setRangeUpgrade(false)
      .setData({})
  );
  fap.addUnitPlayer2(
    FAP::makeUnit()
      .setUnitType(BWAPI::UnitTypes::Terran_Marine)
      .setPosition({0, 0})
      .setHealth(BWAPI::UnitTypes::Terran_Marine.maxHitPoints())
      .setShields(BWAPI::UnitTypes::Terran_Marine.maxShields())
      .setFlying(false)
      .setElevation(-1)
      .setAttackerCount(0)
      .setArmorUpgrades(0)
      .setAttackUpgrades(0)
      .setShieldUpgrades(0)
      .setSpeedUpgrade(false)
      .setAttackSpeedUpgrade(false)
      .setAttackCooldownRemaining(0)
      .setStimmed(false)
      .setRangeUpgrade(false)
      .setData({})
  );
```

and then you simulate the combat with `fap.simulate(-1);`, then you can use `fap.getState()` to get the outcome.

**Comment by wanglin95** [comment]
I want to specify a lot of units for each player, then I need to specify these attributes repeatedly for each unit, right? If there are more units, it will be more complicated. Is there any simple method?

**Comment by wanglin95** [comment]
@N00byEdge I create a simulation, but I can't compile it successfully : Can't start the program "E:\FAP-master\FAP-master\x64\Debug\FAP". The FAP project can not generate a debug file, I don't know how to solve it.

**Comment by N00byEdge** [comment]
> I want to specify a lot of units for each player, then I need to specify these attributes repeatedly for each unit, right? If there are more units, it will be more complicated. Is there any simple method?

You could absolutely define a function like the one I created for testing, `testUnit(UnitType)`:
https://github.com/N00byEdge/FAP/blob/master/Tests/TestUnit.hpp#L17
Usage here: https://github.com/N00byEdge/FAP/blob/master/Tests/Combat.cpp#L13

> @N00byEdge I create a simulation, but I can't compile it successfully : Can't start the program "E:\FAP-master\FAP-master\x64\Debug\FAP". The FAP project can not generate a debug file, I don't know how to solve it.

FAP does not generate any files itself. You `#include` it in your own code and it builds straight into your .cpp file.

**Comment by wanglin95** [comment]
@N00byEdge Thank you very much. There is another question, what script is used in combat in FAP?

**Comment by wanglin95** [comment]
@N00byEdge What is the search algorithm for players to perform actions in FAP?  And which script is used?

**Comment by N00byEdge** [comment]
Both players are assumed to attack move towards the closest enemy unit at this moment. FAP is deterministic. It’s generally made for bot writers to make a decision if they want to attack or not while playing the game.

**Comment by N00byEdge** [comment]
If you want to discuss this further, feel free to join the discord to discuss with other BWAPI developers: https://discord.gg/DqvHsq9 as this is not an issue.

**Comment by wanglin95** [comment]
@N00byEdge Based on the enemy's army, I chose the units for the other player.Now I want to see if the units I selected can win. Attack -Closest script is not the best script, so I wonder if it is feasible to simulate with FAP?

**Comment by bftjoe** [comment]
You have to implement that yourself like Locutus did with dragoon kiting. https://github.com/bmnielsen/Locutus/blob/master/Steamhammer/Source/FAP.cpp
