### ISSUE TITLE
Possible crash if bunker dies to tank splash

### ISSUE THREAD

**Issue by bmnielsen** [N00byEdge/FAP#3]
When a bunker dies in FAP, it is removed from the units vector and four marines are added. If the bunker dies due to tank splash damage, this happens while the units vector is being iterated to apply the splash damage, so if adding the marines causes the vector to resize, it's very likely to cause a crash.

**Comment by N00byEdge** [comment]
Nice catch!

**Comment by N00byEdge** [comment]
Fixed in 468d9d2!
